export {default as Register} from "./Register"
export {default as ChatPage} from "./ChatPage"
export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as MyProfile} from "./MyProfile"